//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package iapiserver

import (
	reflect "reflect"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatAssistant) DeepCopyInto(out *AIChatAssistant) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(string)
		**out = **in
	}
	if in.SuggestedModel != nil {
		in, out := &in.SuggestedModel, &out.SuggestedModel
		*out = new(ProviderModelRefSummary)
		**out = **in
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
	deepcopyGenAnyInto(&in.CustomParameters, &out.CustomParameters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatAssistant.
func (in *AIChatAssistant) DeepCopy() *AIChatAssistant {
	if in == nil {
		return nil
	}
	out := new(AIChatAssistant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatGeneration) DeepCopyInto(out *AIChatGeneration) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	in.StoppedAt.DeepCopyInto(&out.StoppedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatGeneration.
func (in *AIChatGeneration) DeepCopy() *AIChatGeneration {
	if in == nil {
		return nil
	}
	out := new(AIChatGeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatMessage) DeepCopyInto(out *AIChatMessage) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.ModelSnapshot, &out.ModelSnapshot)
	deepcopyGenAnyInto(&in.AssistantSnapshot, &out.AssistantSnapshot)
	if in.AttachmentIcons != nil {
		in, out := &in.AttachmentIcons, &out.AttachmentIcons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatMessage.
func (in *AIChatMessage) DeepCopy() *AIChatMessage {
	if in == nil {
		return nil
	}
	out := new(AIChatMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatMessageTranslation) DeepCopyInto(out *AIChatMessageTranslation) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.ModelSnapshot, &out.ModelSnapshot)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatMessageTranslation.
func (in *AIChatMessageTranslation) DeepCopy() *AIChatMessageTranslation {
	if in == nil {
		return nil
	}
	out := new(AIChatMessageTranslation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatQuickPhrase) DeepCopyInto(out *AIChatQuickPhrase) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Assistant != nil {
		in, out := &in.Assistant, &out.Assistant
		*out = new(AssistantSummary)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatQuickPhrase.
func (in *AIChatQuickPhrase) DeepCopy() *AIChatQuickPhrase {
	if in == nil {
		return nil
	}
	out := new(AIChatQuickPhrase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIChatTopic) DeepCopyInto(out *AIChatTopic) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Assistant != nil {
		in, out := &in.Assistant, &out.Assistant
		*out = new(AssistantSummary)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ProviderModelRefSummary)
		**out = **in
	}
	in.LastActiveAt.DeepCopyInto(&out.LastActiveAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIChatTopic.
func (in *AIChatTopic) DeepCopy() *AIChatTopic {
	if in == nil {
		return nil
	}
	out := new(AIChatTopic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationArtifact) DeepCopyInto(out *ApplicationArtifact) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AssetID != nil {
		in, out := &in.AssetID, &out.AssetID
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationArtifact.
func (in *ApplicationArtifact) DeepCopy() *ApplicationArtifact {
	if in == nil {
		return nil
	}
	out := new(ApplicationArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRun) DeepCopyInto(out *ApplicationRun) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AtomicTaskID != nil {
		in, out := &in.AtomicTaskID, &out.AtomicTaskID
		*out = new(string)
		**out = **in
	}
	if in.ProviderCapabilityID != nil {
		in, out := &in.ProviderCapabilityID, &out.ProviderCapabilityID
		*out = new(string)
		**out = **in
	}
	if in.ProviderCapabilityRevision != nil {
		in, out := &in.ProviderCapabilityRevision, &out.ProviderCapabilityRevision
		*out = new(string)
		**out = **in
	}
	if in.ProviderOperationID != nil {
		in, out := &in.ProviderOperationID, &out.ProviderOperationID
		*out = new(string)
		**out = **in
	}
	if in.WorkflowContractRevision != nil {
		in, out := &in.WorkflowContractRevision, &out.WorkflowContractRevision
		*out = new(string)
		**out = **in
	}
	deepcopyGenAnyInto(&in.CapabilitySourceSnapshot, &out.CapabilitySourceSnapshot)
	deepcopyGenAnyInto(&in.InputSnapshot, &out.InputSnapshot)
	deepcopyGenAnyInto(&in.ExecutionSnapshot, &out.ExecutionSnapshot)
	deepcopyGenAnyInto(&in.OutputMappingSnapshot, &out.OutputMappingSnapshot)
	if in.TaskStatusProjection != nil {
		in, out := &in.TaskStatusProjection, &out.TaskStatusProjection
		*out = new(string)
		**out = **in
	}
	deepcopyGenAnyInto(&in.OutputValues, &out.OutputValues)
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]*ApplicationArtifact, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ApplicationArtifact)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(ApplicationSummary)
		**out = **in
	}
	if in.ApplicationVersion != nil {
		in, out := &in.ApplicationVersion, &out.ApplicationVersion
		*out = new(ApplicationVersionSummary)
		**out = **in
	}
	if in.ApplicationTemplateVersion != nil {
		in, out := &in.ApplicationTemplateVersion, &out.ApplicationTemplateVersion
		*out = new(ApplicationTemplateVersionSummary)
		**out = **in
	}
	if in.ProviderCapability != nil {
		in, out := &in.ProviderCapability, &out.ProviderCapability
		*out = new(ProviderCapabilityRefSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.EngineInstance != nil {
		in, out := &in.EngineInstance, &out.EngineInstance
		*out = new(EngineInstanceRefSummary)
		**out = **in
	}
	if in.AtomicTask != nil {
		in, out := &in.AtomicTask, &out.AtomicTask
		*out = new(AtomicTaskRefSummary)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRun.
func (in *ApplicationRun) DeepCopy() *ApplicationRun {
	if in == nil {
		return nil
	}
	out := new(ApplicationRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Producer != nil {
		in, out := &in.Producer, &out.Producer
		*out = new(RelatedResourceSummary)
		**out = **in
	}
	if in.AtomicTask != nil {
		in, out := &in.AtomicTask, &out.AtomicTask
		*out = new(RelatedResourceSummary)
		**out = **in
	}
	if in.ApplicationRun != nil {
		in, out := &in.ApplicationRun, &out.ApplicationRun
		*out = new(RelatedResourceSummary)
		**out = **in
	}
	if in.CanvasRun != nil {
		in, out := &in.CanvasRun, &out.CanvasRun
		*out = new(RelatedResourceSummary)
		**out = **in
	}
	deepcopyGenAnyInto(&in.Content, &out.Content)
	deepcopyGenAnyInto(&in.Metadata, &out.Metadata)
	if in.Asset != nil {
		in, out := &in.Asset, &out.Asset
		*out = new(UserAssetSummary)
		**out = **in
	}
	if in.AssetVersion != nil {
		in, out := &in.AssetVersion, &out.AssetVersion
		*out = new(AssetVersionSummary)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetBlob) DeepCopyInto(out *AssetBlob) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetBlob.
func (in *AssetBlob) DeepCopy() *AssetBlob {
	if in == nil {
		return nil
	}
	out := new(AssetBlob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetBlobDetail) DeepCopyInto(out *AssetBlobDetail) {
	*out = *in
	deepcopyGenAnyInto(&in.Extend, &out.Extend)
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetBlobDetail.
func (in *AssetBlobDetail) DeepCopy() *AssetBlobDetail {
	if in == nil {
		return nil
	}
	out := new(AssetBlobDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetCategory) DeepCopyInto(out *AssetCategory) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetCategory.
func (in *AssetCategory) DeepCopy() *AssetCategory {
	if in == nil {
		return nil
	}
	out := new(AssetCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetClassificationFlatItem) DeepCopyInto(out *AssetClassificationFlatItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetClassificationFlatItem.
func (in *AssetClassificationFlatItem) DeepCopy() *AssetClassificationFlatItem {
	if in == nil {
		return nil
	}
	out := new(AssetClassificationFlatItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetCollection) DeepCopyInto(out *AssetCollection) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.ParentCollection != nil {
		in, out := &in.ParentCollection, &out.ParentCollection
		*out = new(CollectionSummary)
		**out = **in
	}
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetCollection.
func (in *AssetCollection) DeepCopy() *AssetCollection {
	if in == nil {
		return nil
	}
	out := new(AssetCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetItem) DeepCopyInto(out *AssetItem) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetItem.
func (in *AssetItem) DeepCopy() *AssetItem {
	if in == nil {
		return nil
	}
	out := new(AssetItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetItemClassification) DeepCopyInto(out *AssetItemClassification) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Flat != nil {
		in, out := &in.Flat, &out.Flat
		*out = make([]AssetClassificationFlatItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetItemClassification.
func (in *AssetItemClassification) DeepCopy() *AssetItemClassification {
	if in == nil {
		return nil
	}
	out := new(AssetItemClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetItemRegistration) DeepCopyInto(out *AssetItemRegistration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetItemRegistration.
func (in *AssetItemRegistration) DeepCopy() *AssetItemRegistration {
	if in == nil {
		return nil
	}
	out := new(AssetItemRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetRepresentation) DeepCopyInto(out *AssetRepresentation) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.Content, &out.Content)
	deepcopyGenAnyInto(&in.Metadata, &out.Metadata)
	if in.RetryAfter != nil {
		in, out := &in.RetryAfter, &out.RetryAfter
		*out = (*in).DeepCopy()
	}
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetRepresentation.
func (in *AssetRepresentation) DeepCopy() *AssetRepresentation {
	if in == nil {
		return nil
	}
	out := new(AssetRepresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetUploadSession) DeepCopyInto(out *AssetUploadSession) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.UploadedParts != nil {
		in, out := &in.UploadedParts, &out.UploadedParts
		*out = make([]UploadedPart, len(*in))
		copy(*out, *in)
	}
	if in.PendingLabels != nil {
		in, out := &in.PendingLabels, &out.PendingLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PendingTags != nil {
		in, out := &in.PendingTags, &out.PendingTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetUploadSession.
func (in *AssetUploadSession) DeepCopy() *AssetUploadSession {
	if in == nil {
		return nil
	}
	out := new(AssetUploadSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetVersion) DeepCopyInto(out *AssetVersion) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.Content, &out.Content)
	deepcopyGenAnyInto(&in.Metadata, &out.Metadata)
	deepcopyGenAnyInto(&in.ProcessingError, &out.ProcessingError)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetVersion.
func (in *AssetVersion) DeepCopy() *AssetVersion {
	if in == nil {
		return nil
	}
	out := new(AssetVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomicTask) DeepCopyInto(out *AtomicTask) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.TaskNameMeta.DeepCopyInto(&out.TaskNameMeta)
	deepcopyGenAnyInto(&in.Arguments, &out.Arguments)
	out.RetryPolicy = in.RetryPolicy
	out.TimeoutPolicy = in.TimeoutPolicy
	deepcopyGenAnyInto(&in.CancelPolicy, &out.CancelPolicy)
	deepcopyGenAnyInto(&in.Output, &out.Output)
	in.LastError.DeepCopyInto(&out.LastError)
	if in.RetryOfTask != nil {
		in, out := &in.RetryOfTask, &out.RetryOfTask
		*out = new(AtomicTaskSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.RootTask != nil {
		in, out := &in.RootTask, &out.RootTask
		*out = new(AtomicTaskSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(TaskOwnerSummary)
		(*in).DeepCopyInto(*out)
	}
	in.ScheduleAt.DeepCopyInto(&out.ScheduleAt)
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	in.CanceledAt.DeepCopyInto(&out.CanceledAt)
	if in.ScheduleSource != nil {
		in, out := &in.ScheduleSource, &out.ScheduleSource
		*out = new(ScheduleSourceSummary)
		(*in).DeepCopyInto(*out)
	}
	in.DeletedAt.DeepCopyInto(&out.DeletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomicTask.
func (in *AtomicTask) DeepCopy() *AtomicTask {
	if in == nil {
		return nil
	}
	out := new(AtomicTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomicTaskRefSummary) DeepCopyInto(out *AtomicTaskRefSummary) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomicTaskRefSummary.
func (in *AtomicTaskRefSummary) DeepCopy() *AtomicTaskRefSummary {
	if in == nil {
		return nil
	}
	out := new(AtomicTaskRefSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomicTaskSummary) DeepCopyInto(out *AtomicTaskSummary) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomicTaskSummary.
func (in *AtomicTaskSummary) DeepCopy() *AtomicTaskSummary {
	if in == nil {
		return nil
	}
	out := new(AtomicTaskSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomicTaskTemplate) DeepCopyInto(out *AtomicTaskTemplate) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.SystemName.DeepCopyInto(&out.SystemName)
	deepcopyGenAnyInto(&in.Arguments, &out.Arguments)
	out.RetryPolicy = in.RetryPolicy
	out.TimeoutPolicy = in.TimeoutPolicy
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomicTaskTemplate.
func (in *AtomicTaskTemplate) DeepCopy() *AtomicTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(AtomicTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Canvas) DeepCopyInto(out *Canvas) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.Nodes, &out.Nodes)
	deepcopyGenAnyInto(&in.Connections, &out.Connections)
	deepcopyGenAnyInto(&in.Viewport, &out.Viewport)
	deepcopyGenAnyInto(&in.Logs, &out.Logs)
	deepcopyGenAnyInto(&in.Settings, &out.Settings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Canvas.
func (in *Canvas) DeepCopy() *Canvas {
	if in == nil {
		return nil
	}
	out := new(Canvas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientTlsConfig.
func (in *ClientTlsConfig) DeepCopy() *ClientTlsConfig {
	if in == nil {
		return nil
	}
	out := new(ClientTlsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DAGEdge) DeepCopyInto(out *DAGEdge) {
	*out = *in
	deepcopyGenAnyInto(&in.DataMapping, &out.DataMapping)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DAGEdge.
func (in *DAGEdge) DeepCopy() *DAGEdge {
	if in == nil {
		return nil
	}
	out := new(DAGEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DAGNode) DeepCopyInto(out *DAGNode) {
	*out = *in
	in.Task.DeepCopyInto(&out.Task)
	deepcopyGenAnyInto(&in.InputMapping, &out.InputMapping)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DAGNode.
func (in *DAGNode) DeepCopy() *DAGNode {
	if in == nil {
		return nil
	}
	out := new(DAGNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DAGTaskGroup) DeepCopyInto(out *DAGTaskGroup) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.TaskNameMeta.DeepCopyInto(&out.TaskNameMeta)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]DAGNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]DAGEdge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	deepcopyGenAnyInto(&in.Input, &out.Input)
	deepcopyGenAnyInto(&in.OutputMapping, &out.OutputMapping)
	out.Summary = in.Summary
	deepcopyGenAnyInto(&in.Result, &out.Result)
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	in.TriggeredAt.DeepCopyInto(&out.TriggeredAt)
	if in.RetryOf != nil {
		in, out := &in.RetryOf, &out.RetryOf
		*out = new(TaskOwnerSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleSource != nil {
		in, out := &in.ScheduleSource, &out.ScheduleSource
		*out = new(ScheduleSourceSummary)
		(*in).DeepCopyInto(*out)
	}
	in.DeletedAt.DeepCopyInto(&out.DeletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DAGTaskGroup.
func (in *DAGTaskGroup) DeepCopy() *DAGTaskGroup {
	if in == nil {
		return nil
	}
	out := new(DAGTaskGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoryRetention) DeepCopyInto(out *HistoryRetention) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoryRetention.
func (in *HistoryRetention) DeepCopy() *HistoryRetention {
	if in == nil {
		return nil
	}
	out := new(HistoryRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptItem) DeepCopyInto(out *PromptItem) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Params.DeepCopyInto(&out.Params)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptItem.
func (in *PromptItem) DeepCopy() *PromptItem {
	if in == nil {
		return nil
	}
	out := new(PromptItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptLibrary) DeepCopyInto(out *PromptLibrary) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptLibrary.
func (in *PromptLibrary) DeepCopy() *PromptLibrary {
	if in == nil {
		return nil
	}
	out := new(PromptLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCapabilityRefSummary) DeepCopyInto(out *ProviderCapabilityRefSummary) {
	*out = *in
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(string)
		**out = **in
	}
	if in.OperationName != nil {
		in, out := &in.OperationName, &out.OperationName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCapabilityRefSummary.
func (in *ProviderCapabilityRefSummary) DeepCopy() *ProviderCapabilityRefSummary {
	if in == nil {
		return nil
	}
	out := new(ProviderCapabilityRefSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderLifecycle) DeepCopyInto(out *ProviderLifecycle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderLifecycle.
func (in *ProviderLifecycle) DeepCopy() *ProviderLifecycle {
	if in == nil {
		return nil
	}
	out := new(ProviderLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderModelRefSummary) DeepCopyInto(out *ProviderModelRefSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderModelRefSummary.
func (in *ProviderModelRefSummary) DeepCopy() *ProviderModelRefSummary {
	if in == nil {
		return nil
	}
	out := new(ProviderModelRefSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileSpec) DeepCopyInto(out *ReconcileSpec) {
	*out = *in
	deepcopyGenAnyInto(&in.Config, &out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileSpec.
func (in *ReconcileSpec) DeepCopy() *ReconcileSpec {
	if in == nil {
		return nil
	}
	out := new(ReconcileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileSummary) DeepCopyInto(out *ReconcileSummary) {
	*out = *in
	deepcopyGenAnyInto(&in.Summary, &out.Summary)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileSummary.
func (in *ReconcileSummary) DeepCopy() *ReconcileSummary {
	if in == nil {
		return nil
	}
	out := new(ReconcileSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProjectionEvent) DeepCopyInto(out *RuntimeProjectionEvent) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	deepcopyGenAnyInto(&in.Payload, &out.Payload)
	in.OccurredAt.DeepCopyInto(&out.OccurredAt)
	in.ProjectedAt.DeepCopyInto(&out.ProjectedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProjectionEvent.
func (in *RuntimeProjectionEvent) DeepCopy() *RuntimeProjectionEvent {
	if in == nil {
		return nil
	}
	out := new(RuntimeProjectionEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleReconcileState) DeepCopyInto(out *ScheduleReconcileState) {
	*out = *in
	deepcopyGenAnyInto(&in.Checkpoint, &out.Checkpoint)
	if in.LastStartedAt != nil {
		in, out := &in.LastStartedAt, &out.LastStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastCompletedAt != nil {
		in, out := &in.LastCompletedAt, &out.LastCompletedAt
		*out = (*in).DeepCopy()
	}
	in.LastSummary.DeepCopyInto(&out.LastSummary)
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleReconcileState.
func (in *ScheduleReconcileState) DeepCopy() *ScheduleReconcileState {
	if in == nil {
		return nil
	}
	out := new(ScheduleReconcileState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSourceSummary) DeepCopyInto(out *ScheduleSourceSummary) {
	*out = *in
	if in.ScheduleNameI18n != nil {
		in, out := &in.ScheduleNameI18n, &out.ScheduleNameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ScheduledAt.DeepCopyInto(&out.ScheduledAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSourceSummary.
func (in *ScheduleSourceSummary) DeepCopy() *ScheduleSourceSummary {
	if in == nil {
		return nil
	}
	out := new(ScheduleSourceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleTarget) DeepCopyInto(out *ScheduleTarget) {
	*out = *in
	deepcopyGenAnyInto(&in.Template, &out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleTarget.
func (in *ScheduleTarget) DeepCopy() *ScheduleTarget {
	if in == nil {
		return nil
	}
	out := new(ScheduleTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemNameSpec) DeepCopyInto(out *SystemNameSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemNameSpec.
func (in *SystemNameSpec) DeepCopy() *SystemNameSpec {
	if in == nil {
		return nil
	}
	out := new(SystemNameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAttempt) DeepCopyInto(out *TaskAttempt) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AtomicTask != nil {
		in, out := &in.AtomicTask, &out.AtomicTask
		*out = new(AtomicTaskSummary)
		(*in).DeepCopyInto(*out)
	}
	deepcopyGenAnyInto(&in.InputSnapshot, &out.InputSnapshot)
	deepcopyGenAnyInto(&in.OutputSnapshot, &out.OutputSnapshot)
	in.Error.DeepCopyInto(&out.Error)
	if in.Executor != nil {
		in, out := &in.Executor, &out.Executor
		*out = new(TaskExecutorSummary)
		**out = **in
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAttempt.
func (in *TaskAttempt) DeepCopy() *TaskAttempt {
	if in == nil {
		return nil
	}
	out := new(TaskAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskError) DeepCopyInto(out *TaskError) {
	*out = *in
	in.OccurredAt.DeepCopyInto(&out.OccurredAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskError.
func (in *TaskError) DeepCopy() *TaskError {
	if in == nil {
		return nil
	}
	out := new(TaskError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGroup) DeepCopyInto(out *TaskGroup) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.TaskNameMeta.DeepCopyInto(&out.TaskNameMeta)
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]AtomicTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Strategy = in.Strategy
	out.Summary = in.Summary
	deepcopyGenAnyInto(&in.Result, &out.Result)
	if in.RetryOf != nil {
		in, out := &in.RetryOf, &out.RetryOf
		*out = new(TaskOwnerSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleSource != nil {
		in, out := &in.ScheduleSource, &out.ScheduleSource
		*out = new(ScheduleSourceSummary)
		(*in).DeepCopyInto(*out)
	}
	in.DeletedAt.DeepCopyInto(&out.DeletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGroup.
func (in *TaskGroup) DeepCopy() *TaskGroup {
	if in == nil {
		return nil
	}
	out := new(TaskGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskNameMeta) DeepCopyInto(out *TaskNameMeta) {
	*out = *in
	if in.SystemNameParams != nil {
		in, out := &in.SystemNameParams, &out.SystemNameParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskNameMeta.
func (in *TaskNameMeta) DeepCopy() *TaskNameMeta {
	if in == nil {
		return nil
	}
	out := new(TaskNameMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskOwnerSummary) DeepCopyInto(out *TaskOwnerSummary) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskOwnerSummary.
func (in *TaskOwnerSummary) DeepCopy() *TaskOwnerSummary {
	if in == nil {
		return nil
	}
	out := new(TaskOwnerSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSchedule) DeepCopyInto(out *TaskSchedule) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.TaskNameMeta.DeepCopyInto(&out.TaskNameMeta)
	in.RunAt.DeepCopyInto(&out.RunAt)
	in.Target.DeepCopyInto(&out.Target)
	if in.TargetSummary != nil {
		in, out := &in.TargetSummary, &out.TargetSummary
		*out = new(TaskTargetSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ReconcileSpec != nil {
		in, out := &in.ReconcileSpec, &out.ReconcileSpec
		*out = new(ReconcileSpec)
		(*in).DeepCopyInto(*out)
	}
	out.HistoryRetention = in.HistoryRetention
	in.LastTriggerAt.DeepCopyInto(&out.LastTriggerAt)
	in.NextTriggerAt.DeepCopyInto(&out.NextTriggerAt)
	out.Summary = in.Summary
	if in.LastExecution != nil {
		in, out := &in.LastExecution, &out.LastExecution
		*out = new(TaskScheduleExecution)
		(*in).DeepCopyInto(*out)
	}
	in.DeletedAt.DeepCopyInto(&out.DeletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSchedule.
func (in *TaskSchedule) DeepCopy() *TaskSchedule {
	if in == nil {
		return nil
	}
	out := new(TaskSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskScheduleExecution) DeepCopyInto(out *TaskScheduleExecution) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(TaskScheduleSummary)
		(*in).DeepCopyInto(*out)
	}
	in.ScheduledAt.DeepCopyInto(&out.ScheduledAt)
	in.TriggeredAt.DeepCopyInto(&out.TriggeredAt)
	if in.TargetSummary != nil {
		in, out := &in.TargetSummary, &out.TargetSummary
		*out = new(TaskTargetSummary)
		(*in).DeepCopyInto(*out)
	}
	in.ReconcileSummary.DeepCopyInto(&out.ReconcileSummary)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskScheduleExecution.
func (in *TaskScheduleExecution) DeepCopy() *TaskScheduleExecution {
	if in == nil {
		return nil
	}
	out := new(TaskScheduleExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskScheduleSummary) DeepCopyInto(out *TaskScheduleSummary) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskScheduleSummary.
func (in *TaskScheduleSummary) DeepCopy() *TaskScheduleSummary {
	if in == nil {
		return nil
	}
	out := new(TaskScheduleSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSummary) DeepCopyInto(out *TaskSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSummary.
func (in *TaskSummary) DeepCopy() *TaskSummary {
	if in == nil {
		return nil
	}
	out := new(TaskSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTargetSummary) DeepCopyInto(out *TaskTargetSummary) {
	*out = *in
	if in.NameI18n != nil {
		in, out := &in.NameI18n, &out.NameI18n
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTargetSummary.
func (in *TaskTargetSummary) DeepCopy() *TaskTargetSummary {
	if in == nil {
		return nil
	}
	out := new(TaskTargetSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// deepcopyGenVisit identifies reference values that have already been copied.
type deepcopyGenVisit struct {
	typ reflect.Type
	ptr uintptr
	len int
	cap int
}

// deepcopyGenAnyValue recursively copies the dynamic value stored in interface{} / any.
func deepcopyGenAnyValue(in interface{}) interface{} {
	if in == nil {
		return nil
	}
	return deepcopyGenReflectValue(reflect.ValueOf(in), map[deepcopyGenVisit]reflect.Value{}).Interface()
}

// deepcopyGenAnyInto copies a complete typed value through pointers. It avoids
// emitting the value's Go type in generated source, which is necessary when an
// old gengo parser represents a nested any as unnameable_Unsupported.
func deepcopyGenAnyInto(in, out interface{}) {
	inValue := reflect.ValueOf(in)
	outValue := reflect.ValueOf(out)
	if !inValue.IsValid() || !outValue.IsValid() ||
		inValue.Kind() != reflect.Pointer || outValue.Kind() != reflect.Pointer ||
		inValue.IsNil() || outValue.IsNil() {
		return
	}

	copied := deepcopyGenReflectValue(inValue.Elem(), map[deepcopyGenVisit]reflect.Value{})
	if copied.IsValid() && copied.Type().AssignableTo(outValue.Elem().Type()) {
		outValue.Elem().Set(copied)
	}
}

func deepcopyGenReflectValue(in reflect.Value, visited map[deepcopyGenVisit]reflect.Value) reflect.Value {
	if !in.IsValid() {
		return in
	}

	switch in.Kind() {
	case reflect.Interface:
		if in.IsNil() {
			return reflect.Zero(in.Type())
		}
		copied := deepcopyGenReflectValue(in.Elem(), visited)
		out := reflect.New(in.Type()).Elem()
		if copied.IsValid() && copied.Type().AssignableTo(in.Type()) {
			out.Set(copied)
		} else if copied.IsValid() && copied.Type().Implements(in.Type()) {
			out.Set(copied)
		} else {
			out.Set(in)
		}
		return out

	case reflect.Pointer:
		if in.IsNil() {
			return reflect.Zero(in.Type())
		}
		key := deepcopyGenVisit{typ: in.Type(), ptr: in.Pointer()}
		if copied, ok := visited[key]; ok {
			return copied
		}
		out := reflect.New(in.Type().Elem())
		visited[key] = out
		out.Elem().Set(deepcopyGenReflectValue(in.Elem(), visited))
		return out

	case reflect.Map:
		if in.IsNil() {
			return reflect.Zero(in.Type())
		}
		key := deepcopyGenVisit{typ: in.Type(), ptr: in.Pointer()}
		if copied, ok := visited[key]; ok {
			return copied
		}
		out := reflect.MakeMapWithSize(in.Type(), in.Len())
		visited[key] = out
		iter := in.MapRange()
		for iter.Next() {
			out.SetMapIndex(iter.Key(), deepcopyGenReflectValue(iter.Value(), visited))
		}
		return out

	case reflect.Slice:
		if in.IsNil() {
			return reflect.Zero(in.Type())
		}
		key := deepcopyGenVisit{typ: in.Type(), ptr: in.Pointer(), len: in.Len(), cap: in.Cap()}
		if copied, ok := visited[key]; ok {
			return copied
		}
		out := reflect.MakeSlice(in.Type(), in.Len(), in.Cap())
		visited[key] = out
		for i := 0; i < in.Len(); i++ {
			out.Index(i).Set(deepcopyGenReflectValue(in.Index(i), visited))
		}
		return out

	case reflect.Array:
		out := reflect.New(in.Type()).Elem()
		for i := 0; i < in.Len(); i++ {
			out.Index(i).Set(deepcopyGenReflectValue(in.Index(i), visited))
		}
		return out

	case reflect.Struct:
		// Preserve unexported fields with a value copy, then recursively copy
		// every exported/settable field.
		out := reflect.New(in.Type()).Elem()
		out.Set(in)
		for i := 0; i < in.NumField(); i++ {
			srcField := in.Field(i)
			dstField := out.Field(i)
			if !dstField.CanSet() || !srcField.CanInterface() {
				continue
			}
			copied := deepcopyGenReflectValue(srcField, visited)
			if copied.IsValid() && copied.Type().AssignableTo(dstField.Type()) {
				dstField.Set(copied)
			}
		}
		return out

	default:
		// Primitive values are immutable. Functions, channels and unsafe pointers
		// have no general deep-copy semantics and are preserved as-is.
		return in
	}
}
