package iapiserver

const (
	// Task Worker 注册使用的 functionRef。
	TaskWorkerFunctionAgentRuntimeEnsure           = "agent.runtime.ensure"
	TaskWorkerFunctionAgentRuntimeStop             = "agent.runtime.stop"
	TaskWorkerFunctionAppStudioPreviewEnsure       = "appstudio.preview.ensure"
	TaskWorkerFunctionAppStudioPreviewStop         = "appstudio.preview.stop"
	TaskWorkerFunctionAppStudioBuildExecute        = "appstudio.build.execute"
	TaskWorkerFunctionAppStudioProductionReconcile = "appstudio.production.reconcile"
	TaskWorkerFunctionAppStudioProductionStop      = "appstudio.production.stop"
	TaskWorkerFunctionApplicationRun               = "application-platform.run"
	TaskWorkerFunctionComfyUISubmit                = "comfyui.submit"
	TaskWorkerFunctionComfyUIPoll                  = "comfyui.poll"
	TaskWorkerFunctionComfyUICollectPreview        = "comfyui.collect_preview"
	TaskWorkerFunctionScheduleAcquire              = "task.schedule.acquire"

	// TaskWorkerInfrastructureOperationCreate/Start/Stop 是 Task Worker 调用 Infrastructure 的操作类型。
	TaskWorkerInfrastructureOperationCreate = "create"
	TaskWorkerInfrastructureOperationStart  = "start"
	TaskWorkerInfrastructureOperationStop   = "stop"

	// TaskWorkerRuntimeModeJob/Service 是 Task Worker 合同使用的 Runtime 模式。
	TaskWorkerRuntimeModeJob     = "JOB"
	TaskWorkerRuntimeModeService = "SERVICE"

	// Task Worker Runtime 状态用于校验 Worker 执行结果，不复用 InfraRuntime 状态常量。
	TaskWorkerRuntimeStatusRunning   = "RUNNING"
	TaskWorkerRuntimeStatusSucceeded = "SUCCEEDED"
	TaskWorkerRuntimeStatusStopped   = "STOPPED"
	TaskWorkerRuntimeStatusDeleted   = "DELETED"

	TaskWorkerRuntimeEndpointStatusReady   = "READY"
	TaskWorkerRuntimeOutputStatusCollected = "COLLECTED"

	TaskWorkerEndpointVisibilityInternal       = "INTERNAL"
	TaskWorkerEndpointVisibilityUserAccessible = "USER_ACCESSIBLE"
	TaskWorkerRuntimeHealthStatusHealthy       = "HEALTHY"
	TaskWorkerBuildValidationStatusPassed      = "PASSED"

	TaskWorkerActionSuspend = "SUSPEND"
	TaskWorkerActionStop    = "STOP"
	TaskWorkerActionDelete  = "DELETE"

	TaskWorkerAgentRuntimeOperationStart   = "START"
	TaskWorkerAgentRuntimeOperationRecover = "RECOVER"

	TaskWorkerAgentRuntimeRestartPolicyNever     = "NEVER"
	TaskWorkerAgentRuntimeRestartPolicyOnFailure = "ON_FAILURE"
	TaskWorkerAgentRuntimeRestartPolicyAlways    = "ALWAYS"

	TaskWorkerDeploymentReasonDeploy   = "DEPLOY"
	TaskWorkerDeploymentReasonUpgrade  = "UPGRADE"
	TaskWorkerDeploymentReasonRollback = "ROLLBACK"

	TaskWorkerRetryBackoffExponential = "EXPONENTIAL_BACKOFF"

	// Task Worker 调用 Infrastructure 时使用的固定服务和归属域。
	TaskWorkerRequestingServiceTaskCenter = "task-center"
	TaskWorkerOwnerDomainAgent            = "agent"
	TaskWorkerOwnerDomainAppStudio        = "appstudio"

	// Agent 与 AppStudio Worker 使用的业务枚举和 Runtime Profile。
	TaskWorkerAgentKindPlatform                    = "platform"
	TaskWorkerAgentKindCoding                      = "coding"
	TaskWorkerWorkspaceTypeAgent                   = "agent"
	TaskWorkerWorkspaceTypeStudio                  = "studio"
	TaskWorkerEnvironmentPreview                   = "preview"
	TaskWorkerEnvironmentProduction                = "production"
	TaskWorkerAgentRuntimeProfileHermes            = "agent.hermes"
	TaskWorkerAgentRuntimeProfileCoding            = "agent.coding"
	TaskWorkerAppStudioPreviewProfileStaticWeb     = "appstudio.preview.static-web"
	TaskWorkerAppStudioPreviewProfileWebBackend    = "appstudio.preview.web-backend"
	TaskWorkerAppStudioBuildProfileStaticWeb       = "appstudio.build.static-web"
	TaskWorkerAppStudioBuildProfileWebBackend      = "appstudio.build.web-backend"
	TaskWorkerAppStudioProductionProfileStaticWeb  = "studioapp.runtime.static-web"
	TaskWorkerAppStudioProductionProfileWebBackend = "studioapp.runtime.web-backend"

	// Task Worker 处理的受控跨模块引用前缀。
	TaskWorkerRefPrefixModelAccessSpec         = "model-access://"
	TaskWorkerRefPrefixAgentRuntimeConfig      = "agent-runtime-config://"
	TaskWorkerRefPrefixAgentRuntimeGrant       = "agent-runtime-grant://"
	TaskWorkerRefPrefixAgentWorkspace          = "agent-workspace://"
	TaskWorkerRefPrefixStudioWorkspaceRevision = "studio-workspace-revision://"
	TaskWorkerRefPrefixAppStudioPreviewGrant   = "appstudio-preview-grant://"
	TaskWorkerRefPrefixStudioSnapshot          = "studio-snapshot://"
	TaskWorkerRefPrefixAppStudioBuildConfig    = "appstudio-build-config://"
	TaskWorkerRefPrefixAppStudioBuildGrant     = "appstudio-build-grant://"
	TaskWorkerRefPrefixArtifact                = "artifact://"
	TaskWorkerRefPrefixAppStudioHealthCheck    = "appstudio-health-check://"
	TaskWorkerRefPrefixAppStudioReleaseGrant   = "appstudio-release-grant://"
	TaskWorkerRefPrefixInfraEndpoint           = "infra-endpoint://"
	TaskWorkerRefPrefixInfraOutput             = "infra-output://"

	// Task Worker 产物处理使用的固定类型、前缀和注册模式。
	TaskWorkerArtifactProducerTypeStudioBuild      = "studio_build"
	TaskWorkerArtifactTypeBuildBundle              = "build_bundle"
	TaskWorkerArtifactProcessingProfileBuildBundle = "appstudio-build-bundle-v1"
	TaskWorkerBuildIdempotencyPrefix               = "studio-build:"
	TaskWorkerTaskAttemptLogRefPrefix              = "task-attempt-log:"
	TaskWorkerContentDigestSHA256Prefix            = "sha256:"
	TaskWorkerArtifactRegisterModeCreateAsset      = "create_asset"
	TaskWorkerArtifactRegisterModeAppendVersion    = "append_version"
	TaskWorkerArtifactProcessingChangeTypeReady    = "ready"
	TaskWorkerArtifactProcessingChangeTypeFailed   = "failed"
	TaskWorkerArtifactOutputKeyBuildBundle         = "bundle"
	TaskWorkerArtifactRelativePathBuildBundle      = "bundle.tar.gz"
	TaskWorkerArtifactMediaTypeBuildBundle         = "application/gzip"

	// Task Worker 固定的调度、DAG、任务和消费者标识。
	TaskWorkerConsumerGroupRepresentationOrchestrator    = "task-center-representation-orchestrator"
	TaskWorkerConsumerGroupApplicationRunTerminal        = "application-platform-terminal-projection"
	TaskWorkerConsumerGroupApplicationCatalog            = "workflow-canvas-application-catalog"
	TaskWorkerConsumerGroupApplicationArtifactProjection = "workflow-canvas-application-artifact-projection"
	TaskWorkerConsumerGroupThumbnail                     = "task-center-thumbnail"
	TaskWorkerConsumerGroupArtifactProjection            = "application-platform-artifact-projection"
	TaskWorkerConsumerGroupArtifactProcess               = "task-center-artifact-process"
	TaskWorkerTaskKeyThumbnail                           = "thumbnail"
	TaskWorkerTaskKeyArtifactProcess                     = "artifact-process"
	TaskWorkerTaskKeyRepresentationInspect               = "inspect"
	TaskWorkerTaskKeyRepresentationFinalize              = "finalize"
	TaskWorkerIdempotencyScopeThumbnail                  = "asset-thumbnail"
	TaskWorkerIdempotencyScopeArtifactProcess            = "artifact-process"
	TaskWorkerIdempotencyScopeRepresentations            = "asset-representations"
	TaskWorkerIdempotencyPrefixThumbnail                 = "thumbnail:"
	TaskWorkerIdempotencyPrefixRepresentations           = "asset-representations:"
	TaskWorkerCompositeKeySeparator                      = ":"
	TaskWorkerRepresentationTriggerSourceName            = "asset_version_representation_requested"
	TaskWorkerScheduleNameEngineHealth                   = "application-platform.engine-health"
	TaskWorkerScheduleNameComfyUIObjectInfoRefresh       = "application-platform.comfyui-object-info-refresh"
	TaskWorkerScheduleCronComfyUIObjectInfoRefresh       = "0 0 3 * * *"
	TaskWorkerScheduleCronRepresentationBackfill         = "0 30 3 * * *"
	TaskWorkerTimeZoneUTC                                = "UTC"
	TaskWorkerScheduleReasonMisfire                      = "misfire policy skipped delayed schedule trigger"

	// Task Worker 输出、输入和事件 payload 使用的 map key。
	TaskWorkerKeyAgentID                    = "agent_id"
	TaskWorkerKeyAgentRuntimeID             = "agent_runtime_id"
	TaskWorkerKeyExistingInfraRuntimeID     = "existing_infra_runtime_id"
	TaskWorkerKeyOperation                  = "operation"
	TaskWorkerKeyAgentKind                  = "agent_kind"
	TaskWorkerKeyWorkspaceType              = "workspace_type"
	TaskWorkerKeyWorkspaceID                = "workspace_id"
	TaskWorkerKeyWorkspaceSourceRef         = "workspace_source_ref"
	TaskWorkerKeyRuntimeProfileID           = "runtime_profile_id"
	TaskWorkerKeyRuntimeProfileRevision     = "runtime_profile_revision"
	TaskWorkerKeyModelAccessSpecRef         = "model_access_spec_ref"
	TaskWorkerKeyRuntimeConfigurationRef    = "runtime_configuration_ref"
	TaskWorkerKeyAuthorizationRef           = "authorization_ref"
	TaskWorkerKeyExpectedResourceVersion    = "expected_resource_version"
	TaskWorkerKeyResourceRequirement        = "resource_requirement"
	TaskWorkerKeyLifecyclePolicy            = "lifecycle_policy"
	TaskWorkerKeyRestartPolicy              = "restart_policy"
	TaskWorkerKeyIdleTimeoutSeconds         = "idle_timeout_seconds"
	TaskWorkerKeyMaximumLifetimeSeconds     = "maximum_lifetime_seconds"
	TaskWorkerKeyInfraRuntimeID             = "infra_runtime_id"
	TaskWorkerKeyAction                     = "action"
	TaskWorkerKeyStudioApplicationID        = "studio_application_id"
	TaskWorkerKeyPreviewRuntimeID           = "preview_runtime_id"
	TaskWorkerKeyWorkspaceRevision          = "workspace_revision"
	TaskWorkerKeyWorkspaceRevisionSourceRef = "workspace_revision_source_ref"
	TaskWorkerKeyEndpointVisibility         = "endpoint_visibility"
	TaskWorkerKeyStudioBuildID              = "studio_build_id"
	TaskWorkerKeySourceSnapshotID           = "source_snapshot_id"
	TaskWorkerKeySourceSnapshotDigest       = "source_snapshot_digest"
	TaskWorkerKeySourceSnapshotSourceRef    = "source_snapshot_source_ref"
	TaskWorkerKeyBuildConfigRef             = "build_config_ref"
	TaskWorkerKeyDependencyLockDigest       = "dependency_lock_digest"
	TaskWorkerKeyStudioReleaseID            = "studio_release_id"
	TaskWorkerKeyStudioRuntimeInstanceID    = "studio_runtime_instance_id"
	TaskWorkerKeyStudioApplicationVersionID = "studio_application_version_id"
	TaskWorkerKeyRuntimeConfigID            = "runtime_config_id"
	TaskWorkerKeyArtifactID                 = "artifact_id"
	TaskWorkerKeyArtifactDigest             = "artifact_digest"
	TaskWorkerKeyArtifactSourceRef          = "artifact_source_ref"
	TaskWorkerKeyEnvironment                = "environment"
	TaskWorkerKeyDeploymentReason           = "deployment_reason"
	TaskWorkerKeyHealthCheckRef             = "health_check_ref"
	TaskWorkerKeyApplicationVersionID       = "application_version_id"
	TaskWorkerKeyResolvedInputs             = "resolved_inputs"
	TaskWorkerKeyInProgress                 = "in_progress"
	TaskWorkerKeyThumbnailStatus            = "thumbnail_status"
	TaskWorkerKeyReconcileSummary           = "reconcile_summary"
	TaskWorkerKeyTaskScheduleID             = "task_schedule_id"
	TaskWorkerKeyScheduledAt                = "scheduled_at"
	TaskWorkerKeyScheduleExecutionID        = "schedule_execution_id"
	TaskWorkerKeyStatus                     = "status"
	TaskWorkerKeyReason                     = "reason"
	TaskWorkerKeyTargetID                   = "target_id"
	TaskWorkerKeyTestRunID                  = "test_run_id"
	TaskWorkerKeyQueuePosition              = "queue_position"
	TaskWorkerKeyOutputCount                = "output_count"
	TaskWorkerKeyAssetID                    = "asset_id"
	TaskWorkerKeyThumbnailID                = "thumbnail_id"
	TaskWorkerKeyAssetVersionID             = "asset_version_id"
	TaskWorkerKeyOwnerUserID                = "owner_user_id"
	TaskWorkerKeyMediaType                  = "media_type"
	TaskWorkerKeyProfileVersion             = "profile_version"
	TaskWorkerKeyRepresentationType         = "representation_type"
	TaskWorkerKeyProfile                    = "profile"
	TaskWorkerKeyRequired                   = "required"
	TaskWorkerKeyMaxAttempts                = "max_attempts"
	TaskWorkerKeyContentType                = "content_type"
	TaskWorkerKeySHA256                     = "sha256"
	TaskWorkerKeySizeBytes                  = "size_bytes"
	TaskWorkerKeyMIMEType                   = "mime_type"
	TaskWorkerKeyProcessingProfileVersion   = "processing_profile_version"
	TaskWorkerKeyRuntimeStatus              = "runtime_status"
	TaskWorkerKeyHealthStatus               = "health_status"
	TaskWorkerKeyEndpointRef                = "endpoint_ref"
	TaskWorkerKeyDiagnosticsSummary         = "diagnostics_summary"
	TaskWorkerKeyCompletedAction            = "completed_action"
	TaskWorkerKeyProcessingStatus           = "processing_status"
	TaskWorkerKeyValidationStatus           = "validation_status"
	TaskWorkerKeyLogsRef                    = "logs_ref"
	TaskWorkerKeyMaxActionsPerRun           = "max_actions_per_run"

	// Task Worker 日志事件标识。
	TaskWorkerLogApplicationExecutionWaiting   = "application.execution.waiting"
	TaskWorkerLogApplicationExecutionCompleted = "application.execution.completed"
	TaskWorkerLogAssetThumbnailCompleted       = "asset.thumbnail.completed"
	TaskWorkerLogScheduleReconcileCompleted    = "schedule.reconcile.completed"
	TaskWorkerLogScheduleAcquireStarted        = "schedule.acquire.started"
	TaskWorkerLogScheduleAcquireMisfire        = "schedule.acquire.misfire"
	TaskWorkerLogScheduleAcquireOverlap        = "schedule.acquire.overlap"
	TaskWorkerLogScheduleTargetCreated         = "schedule.target.created"
	TaskWorkerLogComfyUISubmitReady            = "comfyui.submit.ready"
	TaskWorkerLogComfyUIPollRunning            = "comfyui.poll.running"
	TaskWorkerLogComfyUIPollQueued             = "comfyui.poll.queued"
	TaskWorkerLogComfyUIPollCompleted          = "comfyui.poll.completed"
	TaskWorkerLogComfyUIPreviewCollected       = "comfyui.preview.collected"
)
