//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package imachinery

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicQueryParam) DeepCopyInto(out *BasicQueryParam) {
	*out = *in
	out.PagingParams = in.PagingParams
	if in.SearchFields != nil {
		in, out := &in.SearchFields, &out.SearchFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SpecificFilterShadow != nil {
		in, out := &in.SpecificFilterShadow, &out.SpecificFilterShadow
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicQueryParam.
func (in *BasicQueryParam) DeepCopy() *BasicQueryParam {
	if in == nil {
		return nil
	}
	out := new(BasicQueryParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagingParams) DeepCopyInto(out *PagingParams) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagingParams.
func (in *PagingParams) DeepCopy() *PagingParams {
	if in == nil {
		return nil
	}
	out := new(PagingParams)
	in.DeepCopyInto(out)
	return out
}
