package imachinery

import (
	"maps"
	"time"

	"github.com/google/uuid"
	"github.com/wangweihong/gotoolbox/pkg/errors"
	"github.com/wangweihong/gotoolbox/pkg/json"
	"github.com/wangweihong/gotoolbox/pkg/maputil"
	"gorm.io/gorm"
)

// Extend defines a new type used to store extended fields.
type Extend struct {
	maputil.StringAny
}

// String returns the string format of Extend.
func (ext Extend) String() string {
	data, _ := json.Marshal(ext)
	return string(data)
}

// Merge merge extend fields from extendShadow.q
func (ext Extend) Merge(extendShadow string) Extend {
	var extend Extend

	// always trust the extendShadow in the database
	_ = json.Unmarshal([]byte(extendShadow), &extend)
	ext.StringAny = maputil.Copy(extend.StringAny, ext.StringAny)
	return ext
}

// TypeMeta describes an individual object in an API response or request
// with strings representing the type of the object and its API schema version.
// Structures that are versioned or persisted should inline TypeMeta.
type TypeMeta struct {
	// Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// required: false
	Kind string `json:"kind,omitempty"`

	// APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	APIVersion string `json:"apiVersion,omitempty"`
}

// ListMeta describes metadata that synthetic resources must have, including lists and
// various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
type ListMeta struct {
	TotalCount int64 `json:"totalCount,omitempty"`
}

// ObjectMeta is metadata that all persisted resources must have, which includes all objects
// ObjectMeta is also used by gorm.
type ObjectMeta struct {
	// ID is the unique in time and space value for this object. It is typically generated by
	// the storage on successful creation of a resource and is not allowed to change on PUT
	// operations.
	//
	// Populated by the system.
	// Read-only.
	ID string `json:"id,omitempty"   form:"id"   gorm:"primary_key;column:id"`
	// Required: true
	// Name must be unique. Is required when creating resources.
	// Name is primarily intended for creation idempotence and configuration
	// definition.
	Name string `json:"name,omitempty" form:"name" gorm:"column:name;type:varchar(64);not null" binding:"required,name,gt=2,lt=16"`

	// Extend store the fields that need to be added, but do not want to add a new table column, will not be stored in
	// db.
	Extend maputil.StringAny `json:"extend,omitempty" gorm:"-" binding:"omitempty"`

	// ExtendShadow is the shadow of Extend. DO NOT modify directly.
	ExtendShadow string `json:"-" gorm:"column:extend_shadow" binding:"omitempty"`

	// CreatedAt is a timestamp representing the server time when this object was
	// created. It is not guaranteed to be set in happens-before order across separate operations.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	//CreatedAt time.Time `json:"createdAt,omitempty" gorm:"column:created_at"`
	CreatedAt Time `json:"createdAt,omitempty" gorm:"column:created_at"`

	// UpdatedAt is a timestamp representing the server time when this object was updated.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	//UpdatedAt time.Time `json:"updatedAt,omitempty" gorm:"column:updated_at"`
	UpdatedAt Time `json:"updatedAt,omitempty" gorm:"column:updated_at"`

	// Description of object meta.
	Description string `json:"description,omitempty" binding:"omitempty,description"`

	// ResourceVersion
	ResourceVersion int64 `json:"resource_version" gorm:"column:resource_version"`
}

func (obj *ObjectMeta) DeepCopyInto(target *ObjectMeta) {
	target.ID = obj.ID
	target.Name = obj.Name
	target.CreatedAt = obj.CreatedAt
	target.UpdatedAt = obj.UpdatedAt
	target.Description = obj.Description
	target.ResourceVersion = obj.ResourceVersion
	target.ExtendShadow = obj.ExtendShadow

	target.Extend = maputil.Clone(obj.Extend)
	if target.Extend == nil {
		target.Extend = make(map[string]any)
	}

	maps.Copy(target.Extend, obj.Extend)
}

// gorm数据库钩子
// BeforeCreate run before create database record.
func (obj *ObjectMeta) BeforeCreate(tx *gorm.DB) error {
	if obj.ID == "" {
		obj.ID = uuid.New().String()
	}

	obj.ExtendShadow = obj.Extend.String()
	obj.CreatedAt = NewTime(time.Now())
	obj.UpdatedAt = NewTime(time.Now())
	obj.ResourceVersion = 1

	return nil
}

// BeforeUpdate run before update database record.
func (obj *ObjectMeta) BeforeUpdate(tx *gorm.DB) error {
	obj.ExtendShadow = obj.Extend.String()
	obj.UpdatedAt = NewTime(time.Now())
	obj.ResourceVersion++

	return nil
}

// AfterFind run after find to unmarshal an extend shadow string into mExtend struct.
func (obj *ObjectMeta) AfterFind(tx *gorm.DB) error {
	if err := json.Unmarshal([]byte(obj.ExtendShadow), &obj.Extend); err != nil {
		return errors.WithStack(err)
	}

	return nil
}

func (obj *ObjectMeta) SetExtendValue(key string, value any) {
	if key == "" {
		return
	}
	obj.Extend = obj.Extend.Set(key, value)
}
