conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

spring.datasource.url=jdbc:postgresql://postgres:5432/conductor
spring.datasource.username=${CONDUCTOR_POSTGRES_USER:conductor}
spring.datasource.password=${CONDUCTOR_POSTGRES_PASSWORD:conductor}

conductor.indexing.enabled=true
conductor.indexing.type=postgres
conductor.elasticsearch.version=0
conductor.grpc-server.enabled=false
