// generate.go
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"strings"
)

func (g *Generator) findMarkedTypes() []string {
	var markedTypes []string
	fmt.Println("types:", len(g.pkg.types))
	for typeName, typeInfo := range g.pkg.types {
		// 检查注释是否包含标记
		fmt.Println("typeName:", typeName)
		fmt.Println("Comments:", typeInfo.Comments)
		for _, comment := range typeInfo.Comments {
			fmt.Println("comment:", comment.Text)
			if strings.Contains(comment.Text, g.marker) {
				markedTypes = append(markedTypes, typeName)
				break
			}
		}
	}

	return markedTypes
}

func (g *Generator) generate(typeNames []string) error {
	g.buf.Reset()

	// 写入文件头
	g.writeHeader()

	// 为每个标记的类型生成代码
	for _, typeName := range typeNames {
		if err := g.generateForType(typeName); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) writeHeader() {
	g.buf.WriteString("// Code generated by sort-gen; DO NOT EDIT.\n\n")
	g.buf.WriteString("package " + g.pkg.name + "\n\n")
	g.buf.WriteString("// 此文件包含自动生成的 SortFields 方法\n\n")
}

func (g *Generator) generateForType(typeName string) error {
	typeInfo, exists := g.pkg.types[typeName]
	if !exists {
		return fmt.Errorf("未找到类型 %s", typeName)
	}

	// 收集所有字段路径
	fieldPaths := g.collectFieldPaths(typeName, typeInfo.StructType, "", 0, make(map[string]bool))

	// 生成方法
	g.generateSortFieldsMethod(typeName, fieldPaths)

	return nil
}

func (g *Generator) collectFieldPaths(
	typeName string,
	structType *ast.StructType,
	prefix string,
	depth int,
	visited map[string]bool) []string {

	if depth > g.maxDepth {
		return nil
	}

	// 防止循环引用
	if visited[typeName] {
		return nil
	}
	visited[typeName] = true
	defer delete(visited, typeName)

	var fieldPaths []string

	for _, field := range structType.Fields.List {
		// 获取字段名
		fieldName := g.getFieldName(field)
		if fieldName == "" {
			continue
		}

		// 处理嵌入结构体
		if len(field.Names) == 0 {
			// 嵌入结构体 - 递归处理其字段
			if ident, ok := field.Type.(*ast.Ident); ok {
				if embeddedType, exists := g.pkg.types[ident.Name]; exists {
					embeddedPaths := g.collectFieldPaths(
						ident.Name,
						embeddedType.StructType,
						prefix,
						depth+1,
						visited,
					)
					fieldPaths = append(fieldPaths, embeddedPaths...)
				}
			} else if selector, ok := field.Type.(*ast.SelectorExpr); ok {
				// 处理其他包的嵌入类型，如 time.Time
				// 这里简化处理，只添加字段名
				if prefix == "" {
					fieldPaths = append(fieldPaths, g.selectorToString(selector))
				} else {
					fieldPaths = append(fieldPaths, prefix+"."+g.selectorToString(selector))
				}
			}
			continue
		}

		// 构建完整字段路径
		var fullPath string
		if prefix == "" {
			fullPath = fieldName
		} else {
			fullPath = prefix + "." + fieldName
		}

		// 检查字段类型
		if g.isBasicType(field.Type) {
			// 基本类型 - 直接添加
			fieldPaths = append(fieldPaths, fullPath)
		} else if ident, ok := field.Type.(*ast.Ident); ok {
			// 可能是结构体类型
			if nestedType, exists := g.pkg.types[ident.Name]; exists {
				// 递归处理嵌套结构体
				nestedPaths := g.collectFieldPaths(
					ident.Name,
					nestedType.StructType,
					fullPath,
					depth+1,
					visited,
				)
				fieldPaths = append(fieldPaths, nestedPaths...)
			}
			//} else if selector, ok := field.Type.(*ast.SelectorExpr); ok {
		} else if _, ok := field.Type.(*ast.SelectorExpr); ok {
			// 其他包的类型，如 time.Time
			// 这里简化处理，只添加字段名
			fieldPaths = append(fieldPaths, fullPath)
		} else if _, ok := field.Type.(*ast.StarExpr); ok {
			// 指针类型 - 尝试解引用
			if ident := g.dereferenceType(field.Type); ident != nil {
				if nestedType, exists := g.pkg.types[ident.Name]; exists {
					// 递归处理嵌套结构体
					nestedPaths := g.collectFieldPaths(
						ident.Name,
						nestedType.StructType,
						fullPath,
						depth+1,
						visited,
					)
					fieldPaths = append(fieldPaths, nestedPaths...)
				}
			} else {
				// 无法解引用，只添加字段名
				fieldPaths = append(fieldPaths, fullPath)
			}
		}
	}

	return fieldPaths
}

func (g *Generator) getFieldName(field *ast.Field) string {
	// 处理字段名
	var fieldName string
	if len(field.Names) > 0 {
		fieldName = field.Names[0].Name

		// 跳过非导出字段（首字母小写）
		if len(fieldName) > 0 && fieldName[0] >= 'a' && fieldName[0] <= 'z' {
			return ""
		}
	}

	// 处理 JSON tag
	if field.Tag != nil {
		tag := field.Tag.Value
		if strings.HasPrefix(tag, "`") && strings.HasSuffix(tag, "`") {
			tag = tag[1 : len(tag)-1]
			if jsonTag := g.parseJsonTag(tag); jsonTag != "" {
				fieldName = jsonTag
			}
		}
	}

	return fieldName
}

func (g *Generator) parseJsonTag(tag string) string {
	for _, part := range strings.Split(tag, " ") {
		if strings.HasPrefix(part, "json:") {
			jsonValue := strings.TrimPrefix(part, "json:")
			if strings.HasPrefix(jsonValue, "\"") && strings.HasSuffix(jsonValue, "\"") {
				jsonValue = jsonValue[1 : len(jsonValue)-1]
			}
			// 处理 omitempty 等选项
			if commaIdx := strings.Index(jsonValue, ","); commaIdx != -1 {
				jsonValue = jsonValue[:commaIdx]
			}
			// 跳过 "-" 标签
			if jsonValue != "-" {
				return jsonValue
			}
		}
	}
	return ""
}

func (g *Generator) isBasicType(expr ast.Expr) bool {
	switch t := expr.(type) {
	case *ast.Ident:
		basicTypes := map[string]bool{
			"bool":   true,
			"string": true,
			"int":    true, "int8": true, "int16": true, "int32": true, "int64": true,
			"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "uintptr": true,
			"float32": true, "float64": true,
			"byte": true, "rune": true,
		}
		return basicTypes[t.Name]
	case *ast.StarExpr:
		// 指针类型 - 检查指向的类型
		return g.isBasicType(t.X)
	case *ast.SelectorExpr:
		// 其他包的类型，如 time.Time
		if ident, ok := t.X.(*ast.Ident); ok {
			pkgName := ident.Name
			typeName := t.Sel.Name
			// 将 time.Time 视为基本类型
			if pkgName == "time" && typeName == "Time" {
				return true
			}
		}
	}
	return false
}

func (g *Generator) dereferenceType(expr ast.Expr) *ast.Ident {
	if starExpr, ok := expr.(*ast.StarExpr); ok {
		if ident, ok := starExpr.X.(*ast.Ident); ok {
			return ident
		}
	}
	return nil
}

func (g *Generator) selectorToString(selector *ast.SelectorExpr) string {
	if ident, ok := selector.X.(*ast.Ident); ok {
		return ident.Name + "." + selector.Sel.Name
	}
	return ""
}

func (g *Generator) generateSortFieldsMethod(typeName string, fieldPaths []string) {
	receiver := strings.ToLower(typeName[:1])

	g.buf.WriteString(fmt.Sprintf("// SortFields 返回结构体 %s 中所有基本可比较类型字段的路径映射\n", typeName))
	g.buf.WriteString("// 此方法由代码生成器自动生成，请勿手动修改\n")
	g.buf.WriteString(fmt.Sprintf("func (%s %s) SortFields() map[string]struct{} {\n", receiver, typeName))
	g.buf.WriteString("    return map[string]struct{}{\n")

	for _, path := range fieldPaths {
		g.buf.WriteString(fmt.Sprintf("        \"%s\": {},\n", path))
	}

	g.buf.WriteString("    }\n")
	g.buf.WriteString("}\n\n")
}

func (g *Generator) writeOutput(filename string) error {
	// 格式化代码
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		// 如果格式化失败，写入原始内容
		src = g.buf.Bytes()
		fmt.Fprintf(os.Stderr, "警告: 代码格式化失败: %v\n", err)
	}

	return os.WriteFile(filename, src, 0644)
}
